# Generated by Django 4.2.1 on 2023-07-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_postcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
