# Generated by Django 4.2.1 on 2023-05-25 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(upload_to=user.models.profile_picture_file_path),
                ),
                ("bio", models.CharField(max_length=255)),
                (
                    "marriage_status",
                    models.CharField(
                        choices=[
                            ("none", ""),
                            ("single", "Single"),
                            ("married", "Married"),
                            ("relationship", "In relationship"),
                            ("looking", "Looking for someone"),
                        ],
                        default="none",
                        max_length=255,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("none", ""), ("men", "Men"), ("women", "Women")],
                        default="none",
                        max_length=50,
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
